name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build extension
      run: npm run build

    - name: Generate PEM key
      run: openssl genrsa -out key.pem 2048

    - name: Create CRX file
      run: |
        npx crx pack dist --key=key.pem -o 115-offline-download-assistant.crx

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 115-offline-download-assistant
        path: 115-offline-download-assistant.crx
        retention-days: 5
