name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install missing sass dependency
      run: npm install sass

    - name: Build extension using Gulp
      run: npm run gulp-build

    - name: Build CRX using web-ext
      run: npm run build-crx

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 115-offline-download-assistant
        path: artifacts/115-offline-download-assistant-*.zip
        retention-days: 5
