name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build extension
      run: npm run build

    - name: Create ZIP file
      run: npm run zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 115-offline-download-assistant
        path: 115-offline-download-assistant.zip
        retention-days: 5
